swagger: '2.0'
info:
  title: notes I18N
  version: 0.0.1
x-package-name: com.notes.api
paths: { }
definitions:
  I18N:
    type: string
    enum:
      - EMAIL_ALREADY_EXISTS
      - WRONG_FORMAT_OF_EMAIL
      - WRONG_FORMAT_OF_PASSWORD
      - WRONG_PASSWORD
      - FIRSTNAME_REQUIRED
      - LASTNAME_REQUIRED
      - PASSWORD_DOES_NOT_MATCH
      - PASSWORD_REQUIRED
      - NO_AUTHORITIES_TO_CHANGE_THIS_USER
      - NO_AUTHORITIES_TO_VIEW_THIS_USER
      - ALREADY_LIKED
      - NOT_LIKED